### ISSUE TITLE
Release version with Symfony 6 support

### ISSUE THREAD

**Issue by starred-gijs** [Happyr/bref-messenger-failure-strategies#7]
Hi! I see you have added Symfony 6 support in #6 
Do you plan to create a release for it?

**Comment by starred-gijs** [comment]
Friendly ping @Nyholm

**Comment by Nyholm** [comment]
Thank you for the ping. 

Of course. It is released now: https://github.com/Happyr/bref-messenger-failure-strategies/releases/tag/0.4.2

**Comment by starred-gijs** [comment]
Many thanks!
